$table.parse("BL24I-PS-experimentShutter.csv")
#set($dom = "BL24I")
#set($nSerial = 7)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = 7)
#set($title = "PSS - BL24I:LOP 11 EH3AEH3B PERMIT 2 BL24I-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
