$table.parse("BL07B-PS-BOINDs.csv")
#set($dom = "BL07B")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = 1)
#set($splitRowId = -1)
#set($title = "PSS - BL07B:LOPs 9,10,11,12 B/C OC/EC SWITCH ON BEAM ON INDICATORS")
#parse("pss_include.v")
