$table.parse("BL07B-PS-CShutters.csv")
#set($dom = "BL07B")
#set($nSerial = 8)
#set($nParIlk = 3)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL07C: LOP 6 OC SHUTTER PERMIT 3 AND LOP 8 EC SHUTTER PERMIT 4")
#parse("pss_include.v")
