$table.parse("BL06I-PS-eC1IExperimentShutter.csv")
#set($dom = "BL06I")
#set($nSerial = 4)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL06I:EC1I EXPERIMENT SHUTTER")
#parse("pss_include.v")
