$table.parse("BL24I-PS-opticsShutter.csv")
#set($dom = "BL24I")
#set($nSerial = 9)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = 10)
#set($hSplit = 2)
#set($title = "PSS - BL24I:LOP 6 OH1OH2 PERMIT 1 FE24I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
