$table.parse("BL24I-PS-opticsHutch2Enabled.csv")
#set($dom = "BL24I")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = 6)
#set($title = "PSS - BL24I:LOP 10 OH2 OPTICS HUTCH ENABLED")
#parse("pss_include.v")
