$table.parse("BL12I-PS-experimentHutch2Closed.csv")
#set($dom = "BL12I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL12I:EH2 LOP 9 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
