$table.parse("BL12I-PS-experiment2Shutter.csv")
#set($dom = "BL12I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL12I:EH2 LOP 11 PERMIT 2 EXPERIMENT SHUTTER BL12I-PS-SHTR-04")
#parse("pss_include.v")
