$table.parse("BL12I-PS-optics3Shutter.csv")
#set($dom = "BL12I")
#set($nSerial = 7)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 6)
#set($title = "PSS - BL12I:OH3 LOP 6 PERMIT 1 BL12I-PS-SHTR-03 OPTICS SHUTTER")
#parse("pss_include.v")
