env:
  browser: true
  jasmine: true
  jest: true
extends:
  - react-app
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
plugins:
  - react
  - "@typescript-eslint"
  - prettier
rules:
  "@typescript-eslint/no-explicit-any": 0
  import/no-cycle: error
  prettier/prettier:
    - error
    - singleQuote: False
settings:
  react:
    pragma: React
    version: detect
