# Use controls group runners unless overrriden in jobs
default:
  tags:
    - controls

stages:
  - test
  - build-app
  - deploy

.node_test:
  stage: test
  before_script:
    - npm ci
  script:
    - npm test -- --coverage
    - npm run lint
    - npx tsc

node 16:
  extends: .node_test
  image: node:16

build-app:
  stage: build-app
  image: node:16
  script:
    - npm ci
    # Environment variables are captured at build time.
    - export REACT_APP_CONIQL_SOCKET=coniql.diamond.ac.uk:443
    - export REACT_APP_CONIQL_SSL=true
    - export REACT_APP_VERSION=$CI_UPSTREAM_TAG
    - export REACT_APP_BUILD_TIME=$(date --iso=minutes)
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
  trigger: controls/kubernetes/cs-web-proto
  variables:
    CI_UPSTREAM_TAG: $CI_COMMIT_TAG
