default:
  tags:
    - rhel7

stages:
  - test
  - build
  - deploy


.node_test:
  stage: test
  before_script:
    - npm ci
  script:
    - npm test -- --coverage
    - npm run lint
    - npx tsc

node 10:
  extends:
    .node_test
  image: node:10

node 12:
  extends:
    .node_test
  image: node:12

node 14:
  extends:
    .node_test
  image: node:14


deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
  trigger: controls/kubernetes/cs-web-proto
