language: node_js
node_js:
  - 10  # LTS still in maintenance
  - 12  # Active LTS
  - 14  # latest version

addons:
  chrome: stable # make Chrome available

before_install:
  - npm install -g @lhci/cli@0.3.x # install Lighthouse CI

script:
  - npm test -- --coverage
  - npm run prettier-check
  - npm run coveralls
  - npm run lint
  - npx tsc
  - CI=false npm run build

after_success:
  - lhci autorun --upload.target=temporary-public-storage # run lighthouse CI against your static site
