language: node_js
node_js:
  - 11

addons:
  chrome: stable # make Chrome available

before_install:
  - npm install -g @lhci/cli@0.3.x # install Lighthouse CI

script:
  - npm test -- --coverage
  - npm run prettier-check
  - npm run coveralls
  - npm run lint
  - npx tsc
  - npm run build

after_success:
  - lhci autorun --upload.target=temporary-public-storage # run lighthouse CI against your static site
