$table.parse("BL23I-PS-opticsShutter.csv")
#set($dom = "BL23I")
#set($nSerial = 7)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 8)
#set($title = "PSS - BL23I:LOP 6 OH1 PERMIT 1 FE23I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
