$table.parse("BL23I-PS-globalShutter.csv")
#set($dom = "BL23I")
#set($nSerial = 6)
#set($nParIlk = 2)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL23I:LOP 13 G PERMIT 3 FE23I-PS-SHTR-01 PORT SHUTTER")
#parse("pss_include.v")
