$table.parse("BL14I-PS-optics1Shutter.csv")
#set($dom = "BL14I")
#set($nSerial = 10)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL14I:LOP 6 OH1 PERMIT 1 FE14I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
