$table.parse("BL14I-PS-optics2Shutter.csv")
#set($dom = "BL14I")
#set($nSerial = 10)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL14I:LOP 11 OH2 PERMIT 2 BL14I-PS-SHTR-01 OPTICS SHUTTER")
#parse("pss_include.v")
