$table.parse("BL02J-PS-opticsShutter.csv")
#set($dom = "BL02J")
#set($nSerial = 10)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($hSplit = 1)
#set($title = "PSS - BL02J:LOP 6 OH1OH2 PERMIT 1 FE02J-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
