$table.parse("BL02J-PS-optics2Shutter.csv")
#set($dom = "BL02J")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL02J:LOP 11 OH2 PERMIT 2 FE02J-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
