$table.parse("BL10I-PS-opticsShutter.csv")
#set($dom = "BL10I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL10I:LOP 6 OPTICS SHUTTER")
#parse("pss_include.v")
