$table.parse("BL15I-PS-opticsShutter.csv")
#set($dom = "BL15I")
#set($nSerial = 8)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 12)
#set($hSplit = 1)
#set($title = "PSS - BL15I:OH1OH1A LOP 6 PERMIT 1 FE15I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
