$table.parse("BL15I-PS-opticsHutchEnabled.csv")
#set($dom = "BL15I")
#set($nSerial = 7)
#set($nParIlk = 0)
#set($nParLop = 1)
#set($splitRowId = 4)
#set($hSplit = 1)
#set($title = "PSS - BL15I:OH1OH1A LOP 5 OPTICS HUTCH ENABLED")
#parse("pss_include.v")
