$table.parse("BL18B-PS-experimentHutchClosed.csv")
#set($dom = "BL18B")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL18B:LOP 9 EH1 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
