$table.parse("BL11I-PS-experimentHutchEnabled.csv")
#set($dom = "BL11I")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 6)
#set($title = "PSS - BL11I:LOP 10 EH1 EXPERIMENT HUTCH ENABLED")
#parse("pss_include.v")
