$table.parse("BL11I-PS-opticsShutter.csv")
#set($dom = "BL11I")
#set($nSerial = 7)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 8)
#set($title = "PSS - BL11I:LOP 6 OH1 PERMIT 1 FE11I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
