$table.parse("BL11I-PS-experimentShutter.csv")
#set($dom = "BL11I")
#set($nSerial = 10)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL11I:LOP 11 EH1 PERMIT 2 BL11I-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
