$table.parse("BL13I-PS-optics3Shutter.csv")
#set($dom = "BL13I")
#set($nSerial = 10)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL13I:OH3 LOP 6 PERMIT 5 BL13I-PS-SHTR-01 OPTICS SHUTTER")
#parse("pss_include.v")
