$table.parse("BL12I-PS-opticsHutch2Enabled.csv")
#set($dom = "BL12I")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 6)
#set($title = "PSS - BL12I:OH2 LOP 5 OPTICS HUTCH ENABLED")
#parse("pss_include.v")
