$table.parse("BL12I-PS-experimentHutchClosed.csv")
#set($dom = "BL12I")
#set($nSerial = 6)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = 7)
#set($title = "PSS - BL12I:EH1 LOP 9 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
