$table.parse("BL12I-PS-experimentHutchEnabled.csv")
#set($dom = "BL12I")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 6)
#set($title = "PSS - BL12I:EH1 LOP 10 EXPERIMENT HUTCH ENABLED")
#parse("pss_include.v")
