$table.parse("BL12I-PS-experimentShutter.csv")
#set($dom = "BL12I")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 8)
#set($hSplit = 2)
#set($title = "PSS - BL12I:EH1 LOP 11 PERMIT 2 EXPERIMENT SHUTTER BL12I-PS-SHTR-02")
#parse("pss_include.v")
