$table.parse("BL13I-PS-opticsShutter.csv")
#set($dom = "BL13I")
#set($nSerial = 8)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 12)
#set($hSplit = 1)
#set($title = "PSS - BL13I:LOP 6 OH1OH2 PERMIT 1 FE13I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
