$table.parse("BL13I-PS-globalShutter.csv")
#set($dom = "BL13I")
#set($nSerial = 8)
#set($nParIlk = 2)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL13I:LOP 13 G PERMIT 3 FE13I-PS-SHTR-01 PORT SHUTTER")
#parse("pss_include.v")
