$table.parse("BL19I-PS-globalShutter.csv")
#set($dom = "BL19I")
#set($nSerial = 8)
#set($nParIlk = 3)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL19I:G LOP 13 PERMIT 3 FE19I-PS-SHTR-01 PORT SHUTTER")
#parse("pss_include.v")
