$table.parse("BL20I-PS-experimentShutter.csv")
#set($dom = "BL20I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL20I:LOP 11 EH1 PERMIT 2 BL20I-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
