$table.parse("BL15I-PS-experiment2Shutter.csv")
#set($dom = "BL15I")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 8)
#set($hSplit = 1)
#set($title = "PSS - BL15I:EH2 LOP 6 PERMIT 5 BL15I-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
