$table.parse("BL15I-PS-experimentHutch2Closed.csv")
#set($dom = "BL15I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL15I:EH2 LOP 4 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
