$table.parse("BL15I-PS-experimentHutch2Enabled.csv")
#set($dom = "BL15I")
#set($nSerial = 6)
#set($nParIlk = 0)
#set($nParLop = 1)
#set($splitRowId = 6)
#set($title = "PSS - BL15I:EH2 LOP 5 EXPERIMENT HUTCH ENABLED")
#parse("pss_include.v")
