$table.parse("BL15I-PS-experiment3Shutter.csv")
#set($dom = "BL15I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL15I:EH3 LOP 11 PERMIT 6 BL15J-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
