$table.parse("BL09I-PS-experimentShutter.csv")
#set($dom = "BL09I")
#set($nSerial = 10)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL09I:EH1 LOP 11 PERMIT 2 BL09I-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
