$table.parse("BL09I-PS-globalShutter.csv")
#set($dom = "BL09I")
#set($nSerial = 10)
#set($nParIlk = 2)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL09I:G LOP 13 PERMIT 3 FE09I-PS-SHTR-01 PORT SHUTTER")
#parse("pss_include.v")
