$table.parse("BL09I-PS-opticsShutter.csv")
#set($dom = "BL09I")
#set($nSerial = 10)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL09I:OH1 LOP 6 PERMIT 1 FE09I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
