$table.parse("BL14I-PS-experiment2Shutter.csv")
#set($dom = "BL14I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL14I:LOP 11 EH2 PERMIT 7 EXPERIMENT SHUTTER BL14I-PS-SHTR-03")
#parse("pss_include.v")
