$table.parse("BL21I-PS-opticsShutter.csv")
#set($dom = "BL21I")
#set($nSerial = 7)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = 7)
#set($hSplit = 1)
#set($title = "PSS - BL21I:LOP 6 OH1OH2 PERMIT 1 FE21I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
