$table.parse("BL02J-PS-experimentHutchClosed.csv")
#set($dom = "BL02J")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL02J:LOP 9 EH1 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
