$table.parse("BL22I-PS-experimentHutchClosed.csv")
#set($dom = "BL22I")
#set($nSerial = 6)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL22I:EH1 LOP 9 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
