$table.parse("BL22I-PS-opticsShutter.csv")
#set($dom = "BL22I")
#set($nSerial = 7)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 8)
#set($title = "PSS - BL22I:OH1 LOP 6 PERMIT 1 FE22I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
