$table.parse("BL22I-PS-opticsHutchClosed.csv")
#set($dom = "BL22I")
#set($nSerial = 6)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = 6)
#set($title = "PSS - BL22I:OH1 LOP 4 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
