$table.parse("BL22I-PS-experimentShutter.csv")
#set($dom = "BL22I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL22I:EH1 LOP 11 PERMIT 2 BL22I-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
