$table.parse("BL05I-PS-opticsShutter.csv")
#set($dom = "BL05I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL05I:LOP 6 OPTICS SHUTTER")
#parse("pss_include.v")
