$table.parse("BL05I-PS-globalShutterOk.csv")
#set($dom = "BL05I")
#set($nSerial = 2)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL05I:LOP 11 G SHUTTER OK")
#parse("pss_include.v")
