$table.parse("BL11K-PS-globalShutter.csv")
#set($dom = "BL11K")
#set($nSerial = 6)
#set($nParIlk = 2)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL11K:G LOP 13 PERMIT 3 FE11K-PS-SHTR-01 PORT SHUTTER")
#parse("pss_include.v")
