$table.parse("BL11K-PS-opticsHutchClosed.csv")
#set($dom = "BL11K")
#set($nSerial = 6)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = 6)
#set($title = "PSS - BL11K:OH1 LOP 4 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
