$table.parse("BL07I-PS-experimentShutter.csv")
#set($dom = "BL07I")
#set($nSerial = 7)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 4)
#set($title = "PSS - BL07I:EH1 LOP 11 PERMIT 2 BL07I-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
