$table.parse("BL02I-PS-experimentHutch2Enabled.csv")
#set($dom = "BL02I")
#set($nSerial = 8)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL02I:LOP 10 EH2 EXPERIMENT HUTCH ENABLED")
#parse("pss_include.v")
