$table.parse("BL04I-PS-alarms.csv")
#set($dom = "BL04I")
#set($nSerial = 5)
#set($nParIlk = 0)
#set($nParLop = -1)
#set($splitRowId = 8)
##set($hSplit = 0)
#set($title = "PSS - BL04I: ALARMS")
#parse("pss_include.v")
