$table.parse("BL04I-PS-experimentShutter.csv")
#set($dom = "BL04I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL04I:EH1 LOP 11 PERMIT 2 BL04I-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
