$table.parse("BL21B-PS-experimentHutchClosed.csv")
#set($dom = "BL21B")
#set($nSerial = 10)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL21B:LOP 9 EH1 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
