$table.parse("BL21B-PS-experimentShutter.csv")
#set($dom = "BL21B")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL21B:LOP 11 EH1 PERMIT 2 BL21B-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
