$table.parse("BL14J-PS-experimentShutter.csv")
#set($dom = "BL14J")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL14J:EH1 LOP 11 PERMIT 6 BL14J-PS-SHTR-03 EXPERIMENT SHUTTER")
#parse("pss_include.v")
