$table.parse("BL14J-PS-experimentHutchEnabled.csv")
#set($dom = "BL14J")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 6)
#set($title = "PSS - BL14J:EH1 LOP 10 EXPERIMENT HUTCH ENABLED")
#parse("pss_include.v")
