$table.parse("BL19I-PS-experimentShutter.csv")
#set($dom = "BL19I")
#set($nSerial = 10)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL19I:EH1 LOP 11 PERMIT 2 BL19I-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
