$table.parse("BL19I-PS-opticsShutter.csv")
#set($dom = "BL19I")
#set($nSerial = 10)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL19I:OH1 LOP 6 PERMIT 1 FE19I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
