$table.parse("BL18I-PS-experimentShutter.csv")
#set($dom = "BL18I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL18I:EH1 LOP 11 PERMIT 2 BL18I-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
