$table.parse("BL21I-PS-SpectHallShutterOk.csv")
#set($dom = "BL21I")
#set($nSerial = 2)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL21I:LOP 10 SPECTROMETER HALL SHTR OK")
#parse("pss_include.v")
