$table.parse("BL24B-PS-shutterCascade.csv")
#set($dom = "BL24B")
#set($nSerial = 3)
#set($nParIlk = 2)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($hSplit = 1)
#set($title = "PSS - BL24B: SHUTTER CASCADE")
#parse("pss_include.v")
