$table.parse("BL12I-PS-opticsShutter.csv")
#set($dom = "BL12I")
#set($nSerial = 7)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 8)
#set($title = "PSS - BL12I:LOP 6 OH1 PERMIT 1 FE12I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
