$table.parse("BL02I-PS-experimentShutter.csv")
#set($dom = "BL02I")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL02I:EH1 LOP 11 PERMIT 2 BL02I-PS-SHTR-01 EXPERIMENT SHUTTER")
#parse("pss_include.v")
