$table.parse("BL02I-PS-opticsShutter.csv")
#set($dom = "BL02I")
#set($nSerial = 7)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 8)
#set($title = "PSS - BL02I:OH1 LOP 6 PERMIT 1 FE02I-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
