$table.parse("BL02I-PS-globalShutter.csv")
#set($dom = "BL02I")
#set($nSerial = 8)
#set($nParIlk = 2)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL02I:G LOP 13 PERMIT 3 FE02I-PS-SHTR-01 PORT SHUTTER")
#parse("pss_include.v")
