$table.parse("BL02I-PS-experimentHutchEnabled.csv")
#set($dom = "BL02I")
#set($nSerial = 8)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL02I:EH1 LOP 10 EXPERIMENT HUTCH ENABLED")
#parse("pss_include.v")
