$table.parse("BL16I-PS-globalShutter.csv")
#set($dom = "BL16I")
#set($nSerial = 6)
#set($nParIlk = 2)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL16I:G LOP 13 PERMIT 3 FE16I-PS-SHTR-01 PORT SHUTTER")
#parse("pss_include.v")
