$table.parse("BL16B-PS-opticsShutter.csv")
#set($dom = "BL16B")
#set($nSerial = 7)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 8)
#set($title = "PSS - BL16B:LOP 6 OH1 PERMIT 1 FE16B-PS-SHTR-02 OPTICS SHUTTER")
#parse("pss_include.v")
