$table.parse("BL16B-PS-globalShutter.csv")
#set($dom = "BL16B")
#set($nSerial = 6)
#set($nParIlk = 2)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL16B:LOP 13 G PERMIT 3 FE16B-PS-SHTR-01 PORT SHUTTER")
#parse("pss_include.v")
