$table.parse("BL16B-PS-experimentHutchEnabled.csv")
#set($dom = "BL16B")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 6)
#set($title = "PSS - BL16B:LOP 10 EH1 EXPERIMENT HUTCH ENABLED")
#parse("pss_include.v")
