$table.parse("BL22B-PS-beamlineOk.csv")
#set($dom = "BL22B")
#set($nSerial = 3)
#set($nParIlk = 4)
#set($nParLop = -1)
#set($splitRowId = 4)
#set($title = "PSS - BL22B: BEAMLINE OK")
#parse("pss_include.v")
