$table.parse("BL09I-PS-alarms2.csv")
#set($dom = "BL09I")
#set($nSerial = 5)
#set($nParIlk = 0)
#set($nParLop = -1)
#set($splitRowId = 8)
#set($title = "PSS - BL09I: ALARMS CRATE 2")
#parse("pss_include.v")
