$table.parse("BL09I-PS-eCKExperimentShutter.csv")
#set($dom = "BL09I")
#set($nSerial = 2)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL09I:LOP 9 EC PERMIT 9 EXP. SHUTTER")
#parse("pss_include.v")
