$table.parse("BL09I-PS-eH2JShutterOk.csv")
#set($dom = "BL09I")
#set($nSerial = 2)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL09I:LOP 8 EH2 BL09J-PS-SHTR-02 OK")
#parse("pss_include.v")
