$table.parse("BL04J-PS-globalShutter.csv")
#set($dom = "BL04J")
#set($nSerial = 6)
#set($nParIlk = 3)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL04J:LOP 13 G PERMIT 3 FE04I-PS-SHTR-01 PORT SHUTTER")
#parse("pss_include.v")
