$table.parse("BL04J-PS-opticsShutter.csv")
#set($dom = "BL04J")
#set($nSerial = 7)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 8)
#set($title = "PSS - BL04J:LOP 6 OH1 PERMIT 1 BL04J-PS-SHTR-01 OPTICS SHUTTER")
#parse("pss_include.v")
