$table.parse("BL04J-PS-experimentHutchClosed.csv")
#set($dom = "BL04J")
#set($nSerial = 6)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL04J:LOP 9 EH1 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
