$table.parse("BL04J-PS-experimentHutchEnabled.csv")
#set($dom = "BL04J")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 6)
#set($title = "PSS - BL04J:LOP 10 EH1 EXPERIMENT HUTCH ENABLED")
#parse("pss_include.v")
