$table.parse("BL20J-PS-polychromatorHutchClosed.csv")
#set($dom = "BL20J")
#set($nSerial = 6)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL20J:LOP 4 PH HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
