$table.parse("BL20J-PS-polychromatorShutterHealthy.csv")
#set($dom = "BL20J")
#set($nSerial = 2)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = -1)
#set($title = "PSS - BL20J:LOP 13 POLY. SHUTTER HEALTHY")
#parse("pss_include.v")
