$table.parse("BL20J-PS-experimentHutch2Enabled.csv")
#set($dom = "BL20J")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = 0)
#set($splitRowId = 6)
#set($title = "PSS - BL20J:LOP 10 EH2 EXPERIMENT HUTCH ENABLED")
#parse("pss_include.v")
