$table.parse("BL13J-PS-experimentHutch2Enabled.csv")
#set($dom = "BL13J")
#set($nSerial = 6)
#set($nParIlk = 1)
#set($nParLop = -1)
#set($splitRowId = 6)
#set($title = "PSS - BL13J:LOP 10 EH2 EXPERIMENT HUTCH ENABLED")
#parse("pss_include.v")
