$table.parse("BL13J-PS-experimentHutch2Closed.csv")
#set($dom = "BL13J")
#set($nSerial = 6)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = 6)
#set($title = "PSS - BL13J:LOP 9 EH2 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
