$table.parse("BL13J-PS-experiment2Shutter.csv")
#set($dom = "BL13J")
#set($nSerial = 8)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = -1)
#set($title = "PSS - BL13J:LOP 11 EH2 PERMIT 8 EXPERIMENT SHUTTER BL13J-PS-SHTR-02")
#parse("pss_include.v")
