$table.parse("BL03I-PS-opticsHutchClosed.csv")
#set($dom = "BL03I")
#set($nSerial = 6)
#set($nParIlk = 0)
#set($nParLop = 0)
#set($splitRowId = 5)
#set($title = "PSS - BL03I:OH1 LOP 4 HUTCH SEARCHED & CLOSED")
#parse("pss_include.v")
